### ISSUE TITLE
Lack of nickname and constant refreshing

### ISSUE THREAD

**Issue by TheLastProject** [ChildrenOfUr/coUclient#170]
Okay, so, I registered an account using Mozilla Persona, which was nice and simple. Then, the game started, but I had no nickname.

Attempting to fix it, I refreshed the page, which didn't help. I then logged out, and back in, which didn't help. I then went back to the homepage, and now CoU refreshes about every 5 seconds, forcing me to login again, still having no nickname.

**Comment by ppvk** [comment]
Awesome, thank you. I'm going to look into this right now.

**Comment by ppvk** [comment]
Ok, this problem, the 'no nickname' problem is due to us not having your nickname in OUR database. When we create a Persona account we are only allowing persona to vouch for our identity, not actually creating an account for CoU. If you to our Forums page on the main site, and 'sign in' there it will prompt you for a username. Once you submit one, you'll be able to see it in game. I'm going to temporarily fix this bug by autoreferring people to that page.

**Comment by ppvk** [comment]
This should be fixed in commit: 8a8542c474d355c3b0eb60f234139a216baf4176

Thanks for reporting, and sorry it took so long!
