### ISSUE TITLE
Keyboard shortcuts for UI controls

### ISSUE THREAD

**Issue by Klikini** [ChildrenOfUr/coUclient#188]
- Esc to close current window ✓
- Tab to chat pane
- M (while focused in game) to open the map ✓

**Comment by DiscountBinNinja** [comment]
Also: keyboard commands to interact with signs, click on trees etc, esc to go from chat to game screen.

**Comment by Klikini** [comment]
@DiscountBinNinja I believe the keyboard can already control trees and signs.

**Comment by DiscountBinNinja** [comment]
I can't click on trees though, and my keyboard controls on the signs is iffy. I also can't click on the few piggies I've seen.

**Comment by RobertMcDermot** [comment]
@DiscountBinNinja You're right that clicking at the moment is iffy. I believe it is possible (or at least it used to be, I honestly never liked clicking so I don't use/test it much) to click on trees/piggies as long as you are standing close enough to touch them. The way the code worked when I made it was to check if you were touching the entity and if so, a right click would allow the interaction menu to appear.

The reason that I did it this way instead of walking you close enough to interact (if possible) was because we didn't have any method to auto-walk implemented yet and I didn't want to get into that yet. If you could try right-clicking a tree while being close enough that it's highlighted and tell me if that works, I would appreciate it.

As for the street signs, could you be any more specific on what 'iffy' means so that I can diagnose the problem there?

**Comment by Klikini** [comment]
Closing: no response for a month
