### ISSUE TITLE
Wrong street sign

### ISSUE THREAD

**Issue by DiscountBinNinja** [ChildrenOfUr/coUclient#192]
Sometimes moving from one street to another deposits me at the wrong street sign.  It seems consistent, do you want me to screencap and report every instance?

**Comment by RobertMcDermot** [comment]
I don't think it's necessary to screencap them or to give every instance, but if you could tell me a few that you notice, I may be able to track the problem down.

**Comment by Klikini** [comment]
![image](https://cloud.githubusercontent.com/assets/1693960/8261423/29db9b90-1690-11e5-954a-1afb5b6b39d9.png)

Flipside, far right

**Comment by RobertMcDermot** [comment]
Due to correcting street names that were previously shown as bogus values (Ian_street_r or G.A.A.A.20 or other nonsense like that), I believe this issue will also be fixed. This is because when changing streets via a sign post, it tries to put you next to the signpost in the next street with a matching label. Since these labels are all corrected now, there should not be an issue.

If you experience this again, please feel free to comment here or open a new issue. In figuring out the cause, it would be helpful to have at least 1 example of such a problem.
